### ISSUE TITLE
Compilation fails on Mac OSX 10.13.1 0 with configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

### ISSUE THREAD

**Issue by 99darwin** [Divicoin/Divi#1]
It seems the dependence on openssl may pose an issue with compilation on Mac OSX High Sierra. Bitcoin no longer requires openssl as a dependency. The lib cannot be ignored by passing any flags. The latest versions of openssl apparently deprecated a function that would allow compilation in this case.

Potential (temporary?) fix: [PIVX #447](https://github.com/PIVX-Project/PIVX/pull/447)

**Comment by 99darwin** [comment]
Was able to compile by running
```
brew install openssl@1.0
```
then...
```
./configure LDFLAGS='-L/usr/local/opt/openssl/lib' CPPFLAGS='-I/usr/local/opt/openssl/include' PKG_CONFIG_PATH='/usr/local/opt/openssl/lib/pkgconfig' --with-gui=qt5
```

**Comment by dcaldwell-sw** [comment]
PIVX has this posted now as of 3/11/2018, might help:
https://github.com/PIVX-Project/PIVX/commit/aedf80b07dcee5935b6ab01086481a7bb52b4ed3

**Comment by MWaser** [comment]
Problem was resolved by new config.ac.  Nick was successful in compiling and running wallet.
