### ISSUE TITLE
Windows will not sync completely and stays behind Ubuntu

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#10]
Should sync to current block count.

#Running Unbuntu in VirtualBox - Ubuntu Syncs but on same machine Windows 10 always stays at least 10 blocks behind and returns mnsync status as "true" (update reindex partially syncs and then divi stops syncing completely)

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x ] Windows 10

# Install Ubuntu in VirtualBox and start Divi, Install Divi on Windows 10, will not sync even with -reindex

**Comment by HermanHendricks** [comment]
VSO Bug ID #858

**Comment by Guritz** [comment]
Update
Its a port conflict issue - Stopping stopping divi on Ubuntu starts the sync on Windows. Once the sync begins on Windows - Restarting Divi on Ubuntu - results in an ability to sync on Ubuntu.

The fix
Open VirtualBox
File, Host Nework Manager
Create and then configure automatically.

This seems to fix
