### ISSUE TITLE
[UI] Nothing visible when node is fully synced

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#12]
# Expected behavior
I expect it to be visible on the bottom left if the node is fully synced.

# Actual behavior
Once the node is fully synced, the bottom left is empty, however if I hover that empty box, it shows a tooltip. It seems strange that a tooltip appears by hovering an empty box.

# Operating system
Place an 'x' in the box next to your operating system
* [x] Windows 10
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4

# Steps to reproduce the problem
Wait for the node to fully sync, then hover the bottom left box.

**Comment by HermanHendricks** [comment]
VSO #1045 New; Triage;

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by HermanHendricks** [comment]
Fixed
