### ISSUE TITLE
Chain gets corrupted after a while

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#13]
# Expected behavior
I expect the chain to be synced all the time.

# Actual behavior
The chain gets corrupted after a while.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Keep the wallet open. After a while the chain gets corrupted.

It has already been fixed in the following commit:
https://github.com/Divicoin/Divi/commit/d64b472e23e6ed431ce2d47841335954b2f01f6b

It needs to be recompiled so this bugfix is implemented.

**Comment by HermanHendricks** [comment]
Resolved in new build
