### ISSUE TITLE
Make binaries available to each OS

### ISSUE THREAD

**Issue by jcmelati** [Divicoin/Divi#14]
# Expected behavior
Compiled binaries from the latest source code should be available to each OS via direct link.

# Actual behavior
Binaries are not available.

# Missing files
https://github.com/Divicoin/Divi/blob/master/releases/bin/Windows10x86/divid.exe
https://github.com/Divicoin/Divi/blob/master/releases/bin/Windows10x86/divi-cli.exe
https://github.com/Divicoin/Divi/blob/master/releases/bin/Windows10x64/divid.exe
https://github.com/Divicoin/Divi/blob/master/releases/bin/Windows10x64/divi-cli.exe
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu16.04/divid
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu16.04/divi-cli
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu17.10/divid
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu17.10/divi-cli
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu18.04/divid
https://github.com/Divicoin/Divi/blob/master/releases/bin/Ubuntu18.04/divi-cli

**Comment by HermanHendricks** [comment]
VSO #1047, New, Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

- Leads to determine which OS/Versions will be supported

- App to include messaging to inform users of supported OS/versions

**Comment by HermanHendricks** [comment]
Supported operating systems and versions are Mac, Ubuntu 18.04 and Win10x64
