### ISSUE TITLE
Lottery Blocks - Make them as described in our whitepaper and articles

### ISSUE THREAD

**Issue by geoffmccabe** [Divicoin/Divi#15]
# Expected behavior

https://medium.com/diviproject/divis-lottery-blocks-8c323e3b0b4b

# Actual behavior

Not sure yet... I'd like to know if they're functioning the way we anticipated?  And if not, how are they different?   And is it too late too late to modify?

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

**Comment by HermanHendricks** [comment]
This is not a bug. I would suggest a requirements discussion with Divi/AGI leads.

**Comment by HermanHendricks** [comment]
New/Triage

**Comment by HermanHendricks** [comment]
Resolved/Fixed
