### ISSUE TITLE
Possible to open multiple instances of the Divi Desktop Wallet

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#16]
# Expected behavior
I expect the Divi Desktop Wallet to open the existing instance, instead of opening a new one.

# Actual behavior
When starting the Divi Desktop Wallet, a new instance is started, instead of opening the already open instance. There is no limit to how many instances can be open at the same time.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Open the Divi Desktop Wallet. Right after, start it again. Another instance will be opened.

**Comment by HermanHendricks** [comment]
VSO #1048, New, Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by HermanHendricks** [comment]
Fixed
