### ISSUE TITLE
No password is required to open the wallet, confirm transactions etc.

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#17]
# Expected behavior
I expect it to be required to set a password to access the wallet. That password should also be entered to send funds.

# Actual behavior
No password is required to access or send anything

# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.1
* [x] Linux Ubuntu 16.04.4
* [x] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Opening the wallet

**Comment by HermanHendricks** [comment]
VSO #1049, New, Triage

**Comment by HermanHendricks** [comment]
Triaged/Backlog
Feature in requirements review

**Comment by HermanHendricks** [comment]
Added to Backlog for next iteration.
