### ISSUE TITLE
Wallet Receive Tab Blank

### ISSUE THREAD

**Issue by CryptoLexDivi** [Divicoin/Divi#18]
# Expected behavior
Address fields present.
# Actual behavior
After leaving wallet open for some time it seems like all of the address fields on the "Receive" tab are gone. 
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x ] Windows 10

# Steps to reproduce the problem
Run wallet. Let run for a while. Go to Receive tab. Nothing there.

**Comment by MarcelSinteur** [comment]
I think this issue is actually related to https://github.com/Divicoin/Divi/issues/13 as it will try to retrieve 'received transactions' but that is not possible since the RPC won't accept any commands after the chain got corrupted.

**Comment by HermanHendricks** [comment]
VSO #1050, New, Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by Divicoin** [comment]
Fixed in latest builds
