### ISSUE TITLE
No close window option on wallet that closes the wallet completely

### ISSUE THREAD

**Issue by CryptoLexDivi** [Divicoin/Divi#19]
# Expected behavior
Clicking the X window button should close out of the wallet completely.
# Actual behavior
Clicking the X window button just minimizes wallet to system tray. We will need to right-click system tray icon and select Window > Close to exit out of wallet completely.
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x ] Windows 10

# Steps to reproduce the problem

**Comment by MarcelSinteur** [comment]
I think it shouldn't close entirely by default, rather it should give you an option to close it entirely or minimize it to tray.

**Comment by HermanHendricks** [comment]
VSO #1051, New, Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by HermanHendricks** [comment]
Fixed
