### ISSUE TITLE
No Advanced Features/Options

### ISSUE THREAD

**Issue by CryptoLexDivi** [Divicoin/Divi#20]
# Expected behavior
Features form menus such as coin control, map upnp ports, minimize on close, minimize to system tray or task bar, start wallet automatically on startup, encrypt wallet, etc.
# Actual behavior
None of those are present.
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ x] Windows 10

# Steps to reproduce the problem

**Comment by HermanHendricks** [comment]
This is not a bug.  Feature requirements are implemented as specified by Divi.

**Comment by HermanHendricks** [comment]
New/Triage
Feature requirements

**Comment by HermanHendricks** [comment]
Added to Backlog for next iteration.
