### ISSUE TITLE
divid still running after close makes wallet crash

### ISSUE THREAD

**Issue by JeffPrixla1986** [Divicoin/Divi#23]
# Expected behavior
I open my wallet. I close my wallet. I reopen my wallet.

# Actual behavior
I open my wallet. I close my wallet. I reopen my wa... it crash.

# Operating system
Place an 'x' in the box next to your operating system
* [ x] Mac OSX 10.13.4
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
open, close, reopen.

I found that the divid process were not killed if I close the Wallet Gui. That's the reason why it crash. If I kill the divid process and then open again the wallet it works properly.

Discord username: Jeff33140

**Comment by HermanHendricks** [comment]
VSO ID# 1060; New/Triage

**Comment by JeffPrixla1986** [comment]
can be closed, also linked to #26 
not happening on last build
