### ISSUE TITLE
wallet gui console batch not working on OSX

### ISSUE THREAD

**Issue by JeffPrixla1986** [Divicoin/Divi#24]
# Expected behavior
using all cmd from before such as getwalletinfo or so

# Actual behavior
message "Method not found" shows up, nothing happens then.

# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.4
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
install on OSX, click on debug and try something

discord username: Jeff33140

**Comment by HermanHendricks** [comment]
VSO ID #10611; New/Triage

**Comment by JeffPrixla1986** [comment]
can be closed, is linked to #26
