### ISSUE TITLE
On linux stoping and starting crashes gui

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#25]
# Expected behavior
Closing GUI should be able to shutdown and restart

# Actual behavior
If you close the DIVI gui (divid and divi gui stays in memory) Upon restarting machine data in .divi folders is corrupt.
If you remove all the folders backups, blocks, chainstate, database, sporks, zerocoin. But keep the wallet.dat you can restart the divi gui and divid will restart intalling all the folders and re-sync.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ x] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Install
Close the app
Reboot machine

**Comment by HermanHendricks** [comment]
VSO ID #1062; New/Triage

**Comment by HermanHendricks** [comment]
Triaged, Active

**Comment by HermanHendricks** [comment]
Resolved

**Comment by HermanHendricks** [comment]
Fixed
