### ISSUE TITLE
gui wallet keep "loading" to daemon on OSX

### ISSUE THREAD

**Issue by JeffPrixla1986** [Divicoin/Divi#26]
# Expected behavior
connect to daemon, gets all information and run as a gui wallet

# Actual behavior
red line, goes from left to right, I'm looking at it since 2h now... I feel a little dizzy.

# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.4
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
setup on OSX

I checked the divid status with the cli from git. All OK, I even received a tx from guritz (tx: 4a44cf450c2f3b3c74561b7b5ae178cbdc23ddfdf31b838857ca66b1887f7249 ), connection is stable, didn't crashed in one hour but the wallet never make it and all the left panel is not shown.

![capture d ecran 2018-06-28 a 04 42 46](https://user-images.githubusercontent.com/13543562/42010907-3683118a-7a91-11e8-9b66-a21886555c81.png)

**Comment by HermanHendricks** [comment]
VSO ID #1063; New/Triage

**Comment by JeffPrixla1986** [comment]
Found the issue. It is linked to **/etc/hosts** setup. Divi wallet suppose that the computer identify 127.0.0.1 as localhost. Or, if we play with XAMPP or so many of us use different names for the classic "localhost". For example some MAMP removes "localhost" and put something like "MacBookPro1.local".

**Quick fix -> Change /etc/hosts with defaults**
-
So to fix the current issue I have replaced my /etc/hosts with:

`127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost`

Then it worked.

**Fix proposal -> code update**
-
May we try to update divi wallet code to use 127.0.0.1 instead of "localhost"? Then I think it would work without any changes and it will be more robust on custom setups and not only fresh OSX install.

**Comment by gingfinger** [comment]
Unfortunately that fix didn't work at my end. Still stuck with the same problem

**Comment by Jeff86** [comment]
The issue is linked to your localhost. Can you output here the content of your /etc/hosts (doing a « cat /etc/hosts »)

Then can you run the app with console output and paste here a whole segment.

Let’s find the issue :)

**Comment by gingfinger** [comment]
<img width="518" alt="screen shot 2018-06-30 at 06 32 00" src="https://user-images.githubusercontent.com/39313339/42121897-13744830-7c30-11e8-9310-40b766dc86d6.png">


Here is what I get error wise

**Comment by gingfinger** [comment]
Build 15 seems to have fixed this issue for us. Great work
