### ISSUE TITLE
Editing the address label doesn't result in a changed label

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#27]
# Expected behavior
I expect the new label to be reflected in the UI under the 'Address book' tab.

# Actual behavior
The wallet says the label has been updated, however the UI does not reflect the new label.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
1) Add an address to the address book
2) Try to edit the label by clicking on the 'Edit address label' button
3) The address label does not change

**Comment by HermanHendricks** [comment]
VSO ID #1064; New/Triage

**Comment by HermanHendricks** [comment]
Triaged, Active

**Comment by HermanHendricks** [comment]
Resolved

**Comment by HermanHendricks** [comment]
Fixed
