### ISSUE TITLE
Adding an existing address to the address book does not result in an error

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#28]
# Expected behavior
I expect the wallet to return an error when I try to add an address to the address book that already exists

# Actual behavior
The wallet displays a notification that the address has been added to the address book successfully, however it is not actually added to the address book.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
1) Add an address to the address book
2) Add the same address to the address book

**Comment by HermanHendricks** [comment]
VSO ID #1065; New/Triage

**Comment by HermanHendricks** [comment]
Triaged, Active

**Comment by 99darwin** [comment]
Staged for testing

**Comment by Divicoin** [comment]
closed in 1.1.26
