### ISSUE TITLE
GUI History To/From label error

### ISSUE THREAD

**Issue by jcmelati** [Divicoin/Divi#29]
# Expected behavior
Transaction history shows "To:" transaction address

# Actual behavior
Transaction history shows "To/From: " which leads to bad UX.

There is not a "From" address in the transaction.
The address displayed on the transaction is always a "To" address, where the coins are being sent to.
A transaction can be either 'receive' or 'send'. In both cases, the coins are being sent TO that address.
If 'receive', that address is local; is 'send', the address is from an outgoing payment transaction.

# Operating system
Place an 'x' in the box next to your operating system
* [X] Mac OSX 10.13.1
* [x] Linux Ubuntu 16.04.4
* [x] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

**Comment by HermanHendricks** [comment]
VSO ID #1066; New/Triage

**Comment by HermanHendricks** [comment]
Triaged, Requirements Review

**Comment by jcmelati** [comment]
Actualy, this is wrong. 
I think this field is always "TO"

**Comment by jcmelati** [comment]
Actualy, this is not correct.
There is not any "From" address in the transaction.
The address displayed on the transaction is always a "To" address, where the coins are being sent to.
A transaction can be either 'receive' or 'send'. In both cases, the coins are being sent TO that address. 
If 'receive', that address is local; is 'send', the address is from an outgoing payment transaction.

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by 99darwin** [comment]
Staged for testing

**Comment by Guritz** [comment]
![recieptwrong](https://user-images.githubusercontent.com/16604693/45329419-44528700-b515-11e8-98a0-a60c3423c5a1.png)

My edited example :)

![receiptcorrect](https://user-images.githubusercontent.com/16604693/45329434-52080c80-b515-11e8-9dcf-6b8994f62d0b.png)

**Comment by Guritz** [comment]
Sending is a little more clear but it migh be for consistent with the to's and from 's if we do this
![sending](https://user-images.githubusercontent.com/16604693/45330432-4a973200-b51a-11e8-92b2-0b58824a2341.png)

**Comment by 99darwin** [comment]
#12 in vso
