### ISSUE TITLE
Treat failed transaction confirmations on the GUI

### ISSUE THREAD

**Issue by jcmelati** [Divicoin/Divi#30]
# Expected behavior
UI should show "FAIL" description when transactions fails to confirm (confirmations == -1)

# Actual behavior
UI shows "-1 confirmations" which leads to bad UX. User needs to clearly understand that his outgoing transaction had an error during processing and couldnt be confirmed.

# Operating system
Place an 'x' in the box next to your operating system
* [x] Mac OSX 10.13.1
* [x] Linux Ubuntu 16.04.4
* [x] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

**Comment by HermanHendricks** [comment]
VSO ID #1067; New/Triage

**Comment by HermanHendricks** [comment]
Triaged, Active

**Comment by HermanHendricks** [comment]
The confirmations are not failing, this is expected behavior - Closed as By Design
