### ISSUE TITLE
Address book does not populate when select from is used.

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#32]
# Expected behavior
Sending Divi
using the select address from popup - and send divi

# Actual behavior
When select from address book is used - NO addresses populate as choices.
![screenshot from 2018-06-28 18-35-22](https://user-images.githubusercontent.com/16604693/42068658-3a7815ee-7b02-11e8-930c-902b689aae87.png)

Divi Mainnet 1.1.13

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [X] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
On linux
Send to another address using the select from address book option.

**Comment by HermanHendricks** [comment]
VSO ID #1074, New/Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by 99darwin** [comment]
Staged for testing

**Comment by gingfinger** [comment]
This Issue appears to be fixed and is working fine for me now on the latest build

**Comment by 99darwin** [comment]
closed in 1.1.26
