### ISSUE TITLE
Cant use integers as values on Divi desktop console

### ISSUE THREAD

**Issue by jcmelati** [Divicoin/Divi#34]
# Expected behavior
You should be able to use integers as variables when sending RPC calls through DIVI desktop console

# Actual behavior
When using an int as parameter, it returns:

value is type str, expected int

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Try to send transaction from console
sendtoaddress address amount

**Comment by HermanHendricks** [comment]
VSO ID #1076; New/Triage

**Comment by HermanHendricks** [comment]
Triaged/Active

**Comment by Divicoin** [comment]
Fixed in latest builds
