### ISSUE TITLE
Before Confirmation - Sending wallet balance reduces to 0

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#35]
# Expected behavior
Send transaction and reflecting balance should show temporary correct amount before confirmation and finalize or revert balance back upon failure to confirm.

# Actual behavior
Sending a transaction reduces wallet balance to 0 even  if there is an unused balance of DIVI available.
Upon second try it showed dust balance. Attached is second trial image
![screenshot from 2018-06-29 12-54-24](https://user-images.githubusercontent.com/16604693/42112507-dafc6d40-7b9c-11e8-8d25-b43bf54500cb.png)

Happens when sending to another wallet too not just my own. Sent Jeff some yesterday and the balance hit 0 until confirmation. 

After confirmation it does eventually reflect correct balance
![screenshot from 2018-06-29 12-59-46](https://user-images.githubusercontent.com/16604693/42112514-e141792a-7b9c-11e8-95bd-8a43c238ba96.png)

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ x] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Send amount less than max to another wallet. Review account balance until confirmation

**Comment by HermanHendricks** [comment]
VSO ID #1077; New/Triage

**Comment by Divicoin** [comment]
Fixed in latest builds
