### ISSUE TITLE
Balance Inaccurate

### ISSUE THREAD

**Issue by CryptoLexDivi** [Divicoin/Divi#37]
# Expected behavior
Reflect accurate balance
# Actual behavior
I loaded wallet on latest version. Balance was 355 (not sure how). I let it sit for 20 minutes. Balance still 355. I sent 1 Divi. Now balance is 178. After Confirmation balance is now 353.9999 (correct).
What is happening?
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem

**Comment by gingfinger** [comment]
Same issue on OSX version. Seems related to the ghost transaction issue

**Comment by gingfinger** [comment]
Update: I also have the same wallet running on VPS linux install. When I rand desktop OSX for the first time, I used the divi.conf & wallet.dat from the VPS server. SO technically had 2 wallets running at the same time with the same root files. The osx desktop version showed the above error and the VPS didn't. Once I clicked resync on the desktop wallet, the same errors have now shown up on the VPS wallet which has been running for days prior to setup of the desktop one. 2 different instances of the same wallet showing these errors now, with the vps one previously running with no issues

**Comment by HermanHendricks** [comment]
VSO #1103

**Comment by HermanHendricks** [comment]
Closed as fixed in new build (July 5)

**Comment by HermanHendricks** [comment]
Reactivated

**Comment by Divicoin** [comment]
Referenced in https://github.com/Divicoin/Divi/issues/31. Closing for consolidation.
