### ISSUE TITLE
UX issue if Confirm Minimize or Exit it closed

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#39]
# Expected behavior
Click the top right "X" would just close the popup and bring me back to divi-desktop wallet.
![selection_006](https://user-images.githubusercontent.com/16604693/42178933-fd31f0a0-7de6-11e8-958b-af6c11ddd69f.png)

# Actual behavior
Clicking the top right "X" closes the divi-desktop but results in memory present instances of divi and divi-desktop / like minimize.
![selection_007](https://user-images.githubusercontent.com/16604693/42178942-0404dbe0-7de7-11e8-98fd-0d499008d85e.png)

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [X ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem

Just click the "X" and view your system monitor

**Comment by HermanHendricks** [comment]
Build 1.1.16?

**Comment by Guritz** [comment]
Sorry yes

This also results in not being able to open the wallet again until you "kill" all the memory resident divid and divi-desktop

**Comment by HermanHendricks** [comment]
Gotcha, thanks much.

**Comment by oriz456** [comment]
What I have found is it hides the icon, basically the X and the minimize button perform the same action, but the client stays open in the background.

**Comment by Divicoin** [comment]
Fixed in newer builds.
