### ISSUE TITLE
UX - Lock and Unlock

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#41]
# Expected behavior
When the wallet is encrypted it should show that its encrypted (with a lock or somthing)
# Actual behavior
Encrypted wallet doesnt notify you that its encrypted
But does notify you when you temporarily unencrytpted.
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ X] Windows 10

# Steps to reproduce the problem
Encrypt windows 10 wallet on 1.1.17 and un-encrypt to test notifications

**Comment by HermanHendricks** [comment]
VSO #1150 New/Triage

**Comment by Divicoin** [comment]
Fixed in newer versions
