### ISSUE TITLE
Wallet Stuck on "connecting to daemon" Windows 10

### ISSUE THREAD

**Issue by qkum** [Divicoin/Divi#44]
# Wallet starts up and connects to the network

# Wallets starts, error pops up, stucks at #connecting to daemon"

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [X] Windows 10

# Steps to reproduce the problem
How could I know lol.

![divi wallet error](https://user-images.githubusercontent.com/40965179/42423011-e074cc56-82f2-11e8-9ec5-0d713ef841f8.png)
![error diviv wallet 2](https://user-images.githubusercontent.com/40965179/42423014-ea2dee62-82f2-11e8-8405-e0ad530f867b.png)
![error 2 divi wallet](https://user-images.githubusercontent.com/40965179/42423015-ee279996-82f2-11e8-8fd4-ca7040534b22.png)

**Comment by Divicoin** [comment]
Fixed in newer versions
