### ISSUE TITLE
"getstakingstatus" on Desktop Clients returns no info in wallet console

### ISSUE THREAD

**Issue by gingfinger** [Divicoin/Divi#46]
# Expected behavior
On CLI builds the command getstakingstatus returns these values:

  "validtime" : true,
    "haveconnections" : true,
    "walletunlocked" : true,
    "mintablecoins" : true,
    "enoughcoins" : true,
    "mnsync" : true,
    "staking status" : true

Should the desktop wallet console be able to return the same info?

# Actual behavior
On OSX and Windows desktop wallets, when putting the command into the inbuilt wallet console this information is not returned

# Operating system
Place an 'x' in the box next to your operating system
* [ x] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x ] Windows 10

# Steps to reproduce the problem

Have tested on OSX and Windows desktop wallets.

**Comment by Divicoin** [comment]
Fixed in 1.1.25

**Comment by Divicoin** [comment]
Reopening as CLI returns information but debug console in GUI does not.

**Comment by 99darwin** [comment]
Staged for testing

**Comment by gingfinger** [comment]
100% fixed now. Info is being returned as it should on latest GUI build

**Comment by Divicoin** [comment]
closed in 1.1.26
