### ISSUE TITLE
Paging control in app not working

### ISSUE THREAD

**Issue by micgre** [Divicoin/Divi#51]
# Expected behavior is for the paging control to both increase the number of items displayed when selected from the drop-down, and for the arrows to go to another page.

# Nothing happens it doesn't seem like it is hooked up.

# Operating system
Place an 'x' in the box next to your operating system
* [X] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem

**Comment by 99darwin** [comment]
Staged for testing

**Comment by Divicoin** [comment]
closed in 1.1.26
