### ISSUE TITLE
Sending large amounts of DIVI get split up

### ISSUE THREAD

**Issue by micgre** [Divicoin/Divi#52]
# When you are receiving large amounts of funds that it would show up as one transaction.

# It splits up the transaction into 50k transactions and spams you until it is done.

# Operating system
Place an 'x' in the box next to your operating system
* [S] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem

**Comment by 99darwin** [comment]
Closing as not an issue in latest builds.
