### ISSUE TITLE
New block always be mined from the future (30-50s by average)

### ISSUE THREAD

**Issue by nuuneoi** [Divicoin/Divi#54]
New block mined are always got a timestamp of the future by around 30s - 50s.

For example, block number `#19364` with hash `08a8bfaea702d52281afeaea46f9e92a0cd2a5b7570aa3000f24f2987e59b5c3` was mined with timestamp **1531385029** while the time was still at **1531385000**

100% reproducable

**Comment by 99darwin** [comment]
Staged for testing
