### ISSUE TITLE
Block time is still not consistent around 60s

### ISSUE THREAD

**Issue by nuuneoi** [Divicoin/Divi#55]
# Expected behavior
Block time should be around 60s.

# Actual behavior
Block time are now vary around 2s - 300s.

Real time monitoring is available here: http://divi.nuuneoi.com/

![screenshot 2018-07-12 15 48 31](https://user-images.githubusercontent.com/61659/42622732-4d514b9c-85eb-11e8-9338-bd7e6c258705.jpg)

**Comment by 99darwin** [comment]
Staged for testing

**Comment by nuuneoi** [comment]
Still not consistent around 60s. http://divi.nuuneoi.com/

![screenshot 2018-08-21 03 31 34](https://user-images.githubusercontent.com/61659/44365012-bcb7c080-a4f2-11e8-9b2f-7f339ffdc64a.jpg)

**Comment by Divicoin** [comment]
Can you confirm that you are using the latest build, network, fixed seed peers, etc?
