### ISSUE TITLE
shows wallet locked when it isn't

### ISSUE THREAD

**Issue by cryptocorp** [Divicoin/Divi#57]
# Expected behavior
shouldn't show wallet locked on initial startup when no password has been set
# Actual behavior
shows wallet locked on initial startup when no password has been set
# Operating system
Place an 'x' in the box next to your operating system
* [x ] Mac OSX 10.12.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem

**Comment by Divicoin** [comment]
Fixed in version 1.1.25
