### ISSUE TITLE
Encrypting the wallet throws a JavaScript error and crashes the application

### ISSUE THREAD

**Issue by MarcelSinteur** [Divicoin/Divi#60]
# Expected behavior
I expect the 'Encrypt wallet' feature to encrypt the wallet with a password

# Actual behavior
After encrypting the wallet with a password, the application throws a JavaScript error and closes the application.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
1) Open the application
2) Go to Settings
3) Click on 'Encrypt'
4) Fill in password & confirm
5) Application crashes

**Comment by Divicoin** [comment]
Fixed in 1.1.25
