### ISSUE TITLE
In the address book clicking on the address shows an incomplete address

### ISSUE THREAD

**Issue by oriz456** [Divicoin/Divi#63]
# Expected behavior
When hovering over the address in address book, clicking on it opens up a box with a QR code and the address. 
# Actual behavior
However the address starts too far to the right of the box and is missing the last 5 letters/numbers.
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
go to address book. click on the address shown there. Should see something like this:

![image](https://user-images.githubusercontent.com/32154971/42719022-95f3b630-86dd-11e8-89f5-68e99c47e624.png)

**Comment by TravelsAsia** [comment]
I believe this issue is ready to close. The new format prevents the address cutoff issue.
