### ISSUE TITLE
Balance not updated in UI when permanently unlocked via debug console

### ISSUE THREAD

**Issue by justinpatten** [Divicoin/Divi#64]
# Expected behavior
Total balance updates when transactions are sent/received when the wallet is permanently unlocked
Unlocked wallet text in UI properly shows that wallet is permanently unlocked
# Actual behavior
Total balance does not update. Timer is stuck at 5:00
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem

1. Open the debug console in the wallet GUI
2. Type "walletpassphrase mypassphrase 0"
3. Wallet unlocked text states that it is unlocked for 5:00 and it never moves
4. Send DIVI to another address
5. Total balance will not update to reflect that (exiting application and launching again shows proper balance)
6. Receive DIVI or stake
7. Total balance will not update to reflect that

**Comment by justinpatten** [comment]
Another artifact of this is setting the unlock duration to anything over 3600. If I set it to 3610, it will count down from "00:10" and then just stick at "00:00".

**Comment by 99darwin** [comment]
Staged for testing

**Comment by TravelsAsia** [comment]
Odd behavior:

walletpassphrase mypassword 3600  ->  1 hour
walletpassphrase mypassword 5000 -> 23min 15sec
walletpassphrase mypassword 8000 ->13min 15 sec

The GUI also shows a random null

![image](https://user-images.githubusercontent.com/39141658/45318698-a9a17a80-b50b-11e8-8cbb-156b1a9d348e.png)
