### ISSUE TITLE
Staking inconsistent

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#65]
# Expected behavior
Once unlocking wallet staking would become active as node syncs

# Actual behavior
"staking status": "Staking Not Active",
to
"staking status": "Staking Active",

Not consistent and staking rewards are NIL when active

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [X ] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem

Have 10K or more DIVI
Unlock the Windows 1.1.24 Build
Wait for sync, let stake mature?
Review Staking Status
cli and console

**Comment by Divicoin** [comment]
closed in 1.1.26
