### ISSUE TITLE
Unlocking the wallet in Console or CLI - New Icon stays locked

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#67]
# Expected behavior
If I unlock the wallet from console or cli it should show unlocked in every referenced lock in GUI

# Actual behavior
Unlocking by console or cli
Wallet says unlocked on the left 
![selection_043](https://user-images.githubusercontent.com/16604693/42852549-04e2037a-89e6-11e8-8ed4-9f77023324e7.png)
But on the top right is stays locked
![selection_044](https://user-images.githubusercontent.com/16604693/42852559-0fc1866c-89e6-11e8-805d-acb210cd4630.png)

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ X] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Run wallet 1.1.25 in Linux and unlock using console or cli

Allowing you to unlock at that location too

**Comment by gingfinger** [comment]
Further to this issue, if you click the new icon to go through the motion of an unlock, but don't see it through by closing the popup box, the icon changes to unlocked regardless. Icon should stay locked until you fully see through the action.

**Comment by Divicoin** [comment]
closed in 1.1.26
