### ISSUE TITLE
Possible Network issue when connected to a router vs modem - Workaround supplied

### ISSUE THREAD

**Issue by gingfinger** [Divicoin/Divi#69]
# Expected behavior
When calling the command "getnetworkinfo" I'd expect to see ipv4 reachable = true and also local addresses to be populated with My current IP & Port
# Actual behavior
When connected straight to a modem, this expected behaviour is fine and works as it should. When connected via a router, then running "getnetworkinfo" shows no info for local addresses and ipv4 & ipv6 show reachable = false. This does not hinder the staking abilities of the wallet as far as I can tell. In order to allow the correct information to be seen, then the line eternalip=youripaddress needs to be inserted into the divi.conf file. That resolves the issue. However, this will no doubt be lost if on a dynamic ip when my ISP assigns me a different IP address. Unsure if this is actually a problematic issue or not but it is what needs to be done to return the correct network info when behind a router. When setting up a masternode on a dynamic ip and if you stay behind a router, will this cause issues?
# Operating system
Place an 'x' in the box next to your operating system
* [ x] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x ] Windows 10

# Steps to reproduce the problem
I have confirmed this on osx and windows builds.

**Comment by Guritz** [comment]
This is working in

**Comment by Guritz** [comment]
I think this is now working - at least on Linux 1.28

**Comment by oriz456** [comment]
not working for me still
