### ISSUE TITLE
Repeats create wallet each run

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#71]
# Expected behavior
If you close and open a wallet it should display your overview
![selection_066](https://user-images.githubusercontent.com/16604693/43023427-b6213bca-8c1f-11e8-83b7-76ccb44a5d04.png)

# Actual behavior
If I reopen the wallet it gives me the create a new wallet options
![selection_065](https://user-images.githubusercontent.com/16604693/43023453-ccba9cf0-8c1f-11e8-9a21-849d2fc96c58.png)
Over Again

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ X] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Clean Install of Divi 1.1.25 on Ubuntu 18.04
Create Wallet
Go to receiving addresses and name address
(in this case, I sent divi to the clean install)
re-opened new clean install and it asked me to create a new wallet.
It does this everytime

**Comment by Divicoin** [comment]
Closed in 1.1.26
