### ISSUE TITLE
Sending as "public" does not work 

### ISSUE THREAD

**Issue by oriz456** [Divicoin/Divi#72]
# Expected behavior
When checking the "public" option on the left hand side(see screenshot), you should be able to make a public transaction.
# Actual behavior
"Make Payment" stays gray and does not allow you to send.
![image](https://user-images.githubusercontent.com/32154971/43085534-32dab286-8e69-11e8-8df3-e8c09d8a3116.png)
Moreover, when sending WITHOUT using the public option, the confirmation screen still states it will be publicly visible although it is not
![image](https://user-images.githubusercontent.com/32154971/43086469-5f7ddec4-8e6b-11e8-8a96-77fc094c9f34.png)
Additionally, it allows sending(and just chooses Divi by default) even without the user choosing a "currency" and leaving that option blank. And lastly a cosmetic issue, it requires the sendto address 2 lines to fully show(see screenshot above).
# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ ] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem
Go to "Send". Check the "public" option, then fill in the address and the amount and currency, it will still not let you send. Now go back out and back into send, don't check "public", fill in address and amount with no currency, it will allow you to send DIVI.

**Comment by Guritz** [comment]
Just a comment - Its the same on Linux 1.1.25 too

**Comment by Guritz** [comment]
This is an update to the PUBLIC issue for 1.1.26 linux
![publicoption](https://user-images.githubusercontent.com/16604693/44172740-e7d58680-a092-11e8-89c6-63fb5d9ac642.gif)

**Comment by 99darwin** [comment]
#143 in VSO

**Comment by oriz456** [comment]
Confirmed fixed can be closed
