### ISSUE TITLE
 Staking Active but not staking Linux

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#73]
# Expected behavior
Upon unlock with chain synced that it would eventually start to earn rewards

# Actual behavior
Over 100K in DIVI
Staking will show true in all debug and cli areas regarding staking and connections.

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [ x] Linux Ubuntu 18.04.4
* [ ] Windows 10

# Steps to reproduce the problem
Unlock in every with debug/cli and gui or not.
I tried and tested combinations 24 hours at a time and over many days.

Will not stake alone or in a combination of debug/cli or otherwise.

@Giff and I trying to work out connections - I figured out that a VM Host needed to bridge the network connections so the router gives the client machine its own IP. It staked for two rewards.

THEN the kicker!
From @Giff
He suggested I gently spam the walletpassphrase unlock in cli - So I ran unlock 5 times (just a random number I stopped on)
It started staking and has now been staking for 2 days.

**Comment by Divicoin** [comment]
closed in 1.1.26
