### ISSUE TITLE
Windows GUI Version 1.1.26 Not Loading

### ISSUE THREAD

**Issue by cryptoaquarian** [Divicoin/Divi#75]
Expected behavior
When installing and running the GUI for Windows, the GUI should load completely.

Actual behavior
![dividesktop](https://user-images.githubusercontent.com/42388008/44109671-7ac13f16-9fb2-11e8-86d9-bde66a9f2872.JPG)

Blank Screen in Windows GUI

Operating system
Place an 'x' in the box next to your operating system

   Mac OSX 10.13.1
   Linux Ubuntu 16.04.4
   Linux Ubuntu 17.04.4
   Linux Ubuntu 18.04.4
    [ x]  Windows 10 x64

Steps to reproduce the problem
N/A Have enabled divid in the firewall. I got an error message saying the GUI couldn't load, and a prompt to retry. I hit retry and nothing happens. Stays with a blank GUI

**Comment by Divicoin** [comment]
#104 in VSO

**Comment by Divicoin** [comment]
hotfix delivered to beta testers as of this morning.
