### ISSUE TITLE
Need desktop Icons for Linux

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#76]
Neither creates a usable desktop icon.

For the .deb file
It creates a divi-desktop.desktop
but it's looking in the wrong location for exec

[Desktop Entry]
Name=Divi
Comment=Divi, P2P Privacy ecosystem
Exec=/opt/divi/divi %U
Terminal=false
Type=Application
Icon=divi
Path=/opt/divi/
StartupNotify=true
Categories=Finance;

My working desktop icon
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_US]=gnome-panel-launcher
Exec="/opt/Divi Desktop/divi-desktop"
Name[en_US]=DIVI Desktop
Name=DIVI Desktop
Icon=gnome-panel-launcher(need divi icon :) )

Launching it from the tar only launches the divi-desktop which installs all the other files but not a desktop icon

**Comment by Divicoin** [comment]
Closed in 1.1.27
