### ISSUE TITLE
Not receiving rewards unless unlock used excessively

### ISSUE THREAD

**Issue by Guritz** [Divicoin/Divi#77]
Linux build.

Seems like staking really doesn’t kick in unless you enter walletpassphrase “pwd” 0 an ODD number more than 1 including any other unlock(settings or otherwise) usually 3 or more times consecutively.

On this build - Got stake by unlocking using settings and console.

But it wouldn't return rewards.

After a few hours.

Restarted - let sync and sit for an est 15 minutes (was busy)

Then I used the console unlocks" walletpassphrase “pwd” 0", 5 times consecutively. 

The stake and rewards started about an hour after the mojo combo.

For some reason, it works.

This is my config

rpcuser=TempName
rpcpassword=TempSuperPass
rpcport=51473
rpcallowip=127.0.0.1
rpcconnect=127.0.0.1
daemon=1
externalip=MYIPADDRESS

Original password trial and errors were from Giff

**Comment by 99darwin** [comment]
#113 in vso
