### ISSUE TITLE
Encrypt wallet throws error on Windows in 1.1.26

### ISSUE THREAD

**Issue by Divicoin** [Divicoin/Divi#79]
The encrypt wallet functionality throws an error on the Windows version 1.1.26 of the GUI.

![1af22dcc4951edb1a0ae47278843a1cddc0ad4d3_1_613x500](https://user-images.githubusercontent.com/30118309/44160299-d37f9280-a06e-11e8-8a88-9a0bce9c90b6.jpg)

**Comment by Divicoin** [comment]
Bug #112 in VSO

**Comment by TravelsAsia** [comment]
I have not been able to replicate this issue with 1.1.28 / 4.0.10.0
