### ISSUE TITLE
Corrupted block database detected. Do you want to rebuild the block database now? 

### ISSUE THREAD

**Issue by jcmelati** [Divicoin/Divi#8]
# Expected behavior
Daemon should run without corrupting chain.

# Actual behavior
From time to time, daemon crashes and chain gets corrupted. 
When trying to run the server, the following messsage appears:

"Corrupted block database detected. Do you want to rebuild the block database now?"

# Operating system
Place an 'x' in the box next to your operating system
* [ ] Mac OSX 10.13.1
* [ ] Linux Ubuntu 16.04.4
* [ ] Linux Ubuntu 17.04.4
* [x] Linux Ubuntu 18.04.4
* [x] Windows 10

# Steps to reproduce the problem

Leave the node running for a long period.

**Comment by HermanHendricks** [comment]
Issue has been fixed and verified.
