### ISSUE TITLE
Unable to edit the label on an address book entry

### ISSUE THREAD

**Issue by TravelsAsia** [Divicoin/Divi#86]
The wallet will not let you edit the label on an address book entry.

1. Click address book
2. Select the pencil 'edit address label'
3. When you enter the label, the 'add address' box is grey

![editlabel](https://user-images.githubusercontent.com/39141658/45343528-26b20b80-b56f-11e8-8453-cc83dfa6140b.png)

**Comment by 99darwin** [comment]
191 in vso

**Comment by oriz456** [comment]
Fixed.
