### ISSUE TITLE
Can't spam transactions on CLI

### ISSUE THREAD

**Issue by JeffPrixla1986** [Divicoin/Divi#87]
I wanted to do some ping / pong transactions between CLI and GUI. I'm making scripts to test transactions speed and scalability but from now the CLI limit the transaction I can do per sec.

**How to reproduce?**

On cli just send money to an account, then press the top arrow to do the same command and do it again and the we have below issue:

```
 ./divi-cli sendfrom "jefftestmasternode" DGQSHnCqjvD1kD8Hm4dEPt9MGCZ6Y1vi29 4.00000000
ae0136a9c2c29355816887b86030b889fa5e0c7332cfd123ec234f0e9e1728da

./divi-cli sendfrom "jefftestmasternode" DGQSHnCqjvD1kD8Hm4dEPt9MGCZ6Y1vi29 4.00000000
error: {"code":-6,"message":"Insufficient funds"}
```

**Comment by Divicoin** [comment]
Start the daemon with `-spendzeroconfchange`
